db_databc_user: "proxy_databc_test"

webpack_internal_url: "https://testapps-endowment.nrs.bcgov:8000"

oauth_auth_endpoint: "https://test.loginproxy.gov.bc.ca/auth/realms/bcregistry/protocol/openid-connect/auth"
oauth_token_endpoint: "https://test.loginproxy.gov.bc.ca/auth/realms/bcregistry/protocol/openid-connect/token"
oauth_jwks_uri: "https://test.loginproxy.gov.bc.ca/auth/realms/bcregistry/protocol/openid-connect/certs"
oauth_server_metadata_url: "https://test.loginproxy.gov.bc.ca/auth/realms/bcregistry/.well-known/openid-configuration"

tileserv_http_listen_port: "7802"
featureserv_http_listen_port: "9002"
